version: "3.2"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: msc-redis-cache
  redis-message-broker:
    image: ashanust/msc-redis-microservice:latest
    depends_on:
      - redis
    environment:
      - redis.host=msc-redis-cache
    volumes:
      - ./logs/:/logs/
    ports:
      - 7788:7788
